services:
    sonata.admin.album:
        class: Jar\CodeTagMeBundle\Admin\AlbumAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Album" }
        arguments:
            - ~
            - Jar\CodeTagMeBundle\Entity\Album
            - ~
        calls:
            - [ setTranslationDomain, [JarCodeTagMeBundle]]
                
    sonata.admin.section:
        class: Jar\CodeTagMeBundle\Admin\SectionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Section" }
        arguments:
            - ~
            - Jar\CodeTagMeBundle\Entity\Section
            - 'PixSortableBehaviorBundle:SortableAdmin' # define the new controller via the third argument
        calls:
            - [ setTranslationDomain, [JarCodeTagMeBundle]]
            - [ setPositionService, [@pix_sortable_behavior.position]]
